<?php $tendoHelper = Mage::helper('tendopay'); ?>
<div id="tendopay-popup">
    <header class="background-color-lightgrey p-2">
        <div class="text-align-center">
            <img src="https://tendo-static.s3-ap-southeast-1.amazonaws.com/logo/logo.png" class="img-logo"
                 alt="Tendopay Logo">
        </div>
        <div class="text-align-center">
            <h1 class="font-blue-color font-family-verdana heading-text font-weight-500">
                <?php echo $this->__('Get your purchase now, pay it on installments'); ?></h1>
            <!--<p class="font-grey-color font-family-verdana p-font-size"><?php /*echo $this->__('Available up to 10,000 PHP credit.'); */?></p>-->
        </div>
    </header>
    <div class="page-container px-3 px-sm-0">
        <!-- DESKTOP VERSION -->
        <div class="text-align-center row d-md-flex d-block justify-content-center pt-2">
            <div class="px-2 pb-1">
                <img src="https://tendo-static.s3-ap-southeast-1.amazonaws.com/plugins/images/pop_up_img_2.png"
                     class="img-icon" alt="Stopwatch">
                <h3 class="font-blue-color font-family-verdana font-weight-500 h3-font-size"><?php echo $this->__('Quick and Easy'); ?></h3>
                <p class="font-grey-color font-family-verdana p-font-size">
                    <?php echo $this->__('Enter a few pieces of information and get approved quickly.'); ?>
                </p>
            </div>
            <div class="px-2 pb-1">
                <img src="https://tendo-static.s3-ap-southeast-1.amazonaws.com/plugins/images/pop_up_img_1.png"
                     class="img-icon" alt="Dollar icon">
                <h3 class="font-blue-color font-family-verdana font-weight-500 h3-font-size"><?php echo $this->__('No Hidden Fees'); ?></h3>
                <p class="font-grey-color font-family-verdana p-font-size">
                    <?php echo $this->__('Know up front what you\'ll owe, with no hidden costs and no surprises.'); ?>
                </p>
            </div>
        </div>
        <div class="text-align-center">
            <a href="<?php echo $tendoHelper->getTendopayMarketing(); ?>" class="btn font-family-verdana"
               target="_blank"><?php echo $this->__('See If You Qualify'); ?></a>
        </div>
    </div>
    <footer class="text-align-center font-family-verdana background-color-grey">
        <p class="footer"><?php echo $this->__('TendoPay offers a credit line which let\'s you shop on this store and many others. To see if ' .
                'you qualify for a TendoPay credit just click the link above and follow the application instructions. We will ' .
                'give you a decision as quickly as 30 minutes later.'); ?></p>
    </footer>
</div>