<?php

// autoload_psr4.php @generated by Composer

$tendo_vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($tendo_vendorDir);

return array(
    'Psr\\Http\\Message\\' => array($tendo_vendorDir . '/psr/http-message/src'),
    'GuzzleHttp\\Psr7\\' => array($tendo_vendorDir . '/guzzlehttp/psr7/src'),
    'GuzzleHttp\\Promise\\' => array($tendo_vendorDir . '/guzzlehttp/promises/src'),
    'GuzzleHttp\\' => array($tendo_vendorDir . '/guzzlehttp/guzzle/src'),
);
